---
repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: git://github.com/detailyang/pre-commit-shell
    sha: 1.0.2
    hooks:
      - id: shell-lint
        files: \.(sh|bash)$
