#!/bin/bash
cat ~/.jira.d/config-project.yml
./config-extra-vars.sh

case $JIRA_OPERATION in
  create)
    echo "issuetype: Task"
    printf "overrides:\n  priority: Minor\n  sprint_id: $JIRA_EXTRAVAR_SPRINT_ACTIVE_ID\n"
    ;;
  list)
    echo "template: table"
    ;;
esac

cat ~/.jira.d/config-custom-commands.yml
